POST http://localhost:5000/signup
Content-Type: application/json

{
    "username":"",
    "password":"",
    "email" : "",
    "location":"",
    "dob": "",
    "phone": ""
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"",
    "password":""
}

###
GET http://localhost:5000/users
Content-Type: application/json
Authorization: 

###

POST http://localhost:5000/apikey
Content-Type: application/json
Authorization: 

{
    "apiname":"ccfd"
}

###

GET http://localhost:5000/apikey
Content-Type: application/json
Authorization: 

###
DELETE  http://localhost:5000/apikey
Content-Type: application/json
Authorization: 

{
    "apiname":"ccfd"
}

###
POST http://localhost:5000/apikey/verify
Content-Type: application/json
Authorization: 

{
    "apikey":"ccfd_I&OH_u0^8~L!_XTRbIMb/Wo4Q9J5dTe$~0wR@6y$.fraud_detention",
    "secret":"1v7C&YbFNpIl!cp50$Ga^bG.17Zpg4"
}

###

GET http://localhost:5000/getfiles
Content-Type: application/json
Authorization: 

###

POST http://localhost:5000/algorithm/xgboost
Content-Type: application/json
Authorization: 

{
    "file_name":"6231f1b592b2a7c0070cc702_7k37+VpvmFyCFy#h_q+U_creditcard.csv"
}

####

POST http://localhost:5000/frontend/random_forest
Content-Type: application/json

{
    "apikey":"ccfd_I&OH_u0^8~L!_XTRbIMb/Wo4Q9J5dTe$~0wR@6y$.fraud_detention",
    "secret":"1v7C&YbFNpIl!cp50$Ga^bG.17Zpg4"
}


